//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.24 at 05:16:07 PM CST 
//


package gov.anl.aps.small_angle.jlake.properties;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.anl.aps.small_angle.jlake.properties package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Desmearing_QNAME = new QName("jlake-desmearing", "desmearing");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.anl.aps.small_angle.jlake.properties
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FloatUnitType }
     * 
     */
    public FloatUnitType createFloatUnitType() {
        return new FloatUnitType();
    }

    /**
     * Create an instance of {@link DesmearingType }
     * 
     */
    public DesmearingType createDesmearingType() {
        return new DesmearingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DesmearingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "jlake-desmearing", name = "desmearing")
    public JAXBElement<DesmearingType> createDesmearing(DesmearingType value) {
        return new JAXBElement<DesmearingType>(_Desmearing_QNAME, DesmearingType.class, null, value);
    }

}
